# Generated by Django 5.1.2 on 2024-11-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Am_app', '0002_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.EmailField(max_length=254, unique=True)),
                ('email', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=15)),
            ],
        ),
    ]
