# Generated by Django 5.1.2 on 2024-11-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Am_app', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='position',
            new_name='address',
        ),
    ]
