# Generated by Django 5.1.2 on 2024-11-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Am_app', '0004_rename_position_jobapplication_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ongoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
